apiVersion: apps/v1
kind: Deployment
metadata:
  name: converttemperatura
spec:
  replicas: 4
  selector:
    matchLabels:
      app: convert-temperatura
  template:
    metadata:
      labels:
        app: convert-temperatura
    spec:
      containers:
        - name: convert-temperatura
          image: andersontarj/convert-temperatura:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: convert-temperatura
spec:
  selector:
    app: convert-temperatura
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  type: NodePort
