apiVersion: v1
kind: Pod
metadata:
  name: onoxypod
spec:
  containers:
    - name: convert-temp
      image: andersontarj/convert-temperatura:latest 
      ports:
        - containerPort: 8080
      resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "1"
