FROM node
LABEL MAINTAINER = "Anderson Amaral - KubDev/DevOps Pro"
RUN mkdir -p /app/node_modules && chown -R node:node /app
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

EXPOSE 8080
CMD ["node", "server.js"]