apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: converttemperaturareplica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: convert-temperatura
  template:
    metadata:
      labels:
        app: convert-temperatura
    spec:
      containers:
        - name: convert-temperatura
          image: andersontarj/convert-temperatura:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
